export default {
  '/': [
    {
      text: '🚀 快速开始',
      collapsed: true,
      items: [
        { text: '确认环境', link: '/Started/EnvCheck' },
        { text: '安装GsCore', link: '/Started/InstallCore' },
        { text: '启动GsCore', link: '/Started/StartCore' },
        { text: '使用Docker运行GsCore', link: '/Started/DockerCore' },
        { text: '宝塔面板部署GsCore', link: '/Started/BTPanel' },
        { text: '配置GsCore', link: '/Started/CoreConfig' },
        { text: '🔒️ 安全配置', link: '/Started/Secure' },
        { text: '网页控制台', link: '/Started/WebConsole' },
      ],
    },
    {
      text: ' 🤖 链接支持Bot',
      collapsed: true,
      items: [
        { text: 'NoneBot2', link: '/LinkBots/NoneBot2' },
        { text: 'HoshinoBot', link: '/LinkBots/HoshinoBot' },
        { text: '适配Bot列表', link: '/LinkBots/AdapterList' },
      ],
    },
    {
      text: '🔧 安装插件',
      collapsed: true,
      items: [
        { text: '安装插件', link: '/InstallPlugins/InstallPlugins' },
        { text: '插件列表', link: '/InstallPlugins/PluginsList' },
      ],
    },
    {
      text: ' 🚀 进阶介绍',
      collapsed: true,
      items: [
        { text: '🧠 AI配置', link: '/Advance/AIConfig' },
        { text: '概念理解', link: '/Advance/BaseInfo' },
        { text: '数据存储结构', link: '/Advance/DataStruct' },
        { text: '配置数据库', link: '/Advance/Database' },
        { text: '常见问题', link: '/FAQ/' },
        { text: '绑定账号', link: '/Advance/BindDevice' },
        { text: '转URL图片发送', link: '/Advance/TransURL' },
        { text: 'MD模板和按钮模板', link: '/Advance/MarkdownTemplate' },
        { text: 'Core配置项', link: '/Advance/CoreConfig' },
        { text: 'HTTP调用', link: '/Advance/HTTPCall' },
      ],
    },
    {
      text: ' 🧠 AI功能',
      collapsed: true,
      items: [
        { text: 'AI功能概述', link: '/AIFeatures/' },
        { text: 'AI插件编写简介', link: '/AIFeatures/ai_core_api_for_plugins' },
        { text: '触发器桥接(to_ai)', link: '/AIFeatures/TriggerBridge' },
        { text: '工具注册', link: '/AIFeatures/Tools' },
        { text: '知识库注册', link: '/AIFeatures/KnowledgeBase' },
        { text: 'Agent创建', link: '/AIFeatures/Agent' },
        { text: '别名注册', link: '/AIFeatures/Alias' },
        { text: 'MCP工具集成', link: '/AIFeatures/MCP' },
        { text: '内置工具', link: '/AIFeatures/BuiltinTools' },
        { text: 'Skills系统', link: '/AIFeatures/Skills' },
        { text: '完整示例', link: '/AIFeatures/Examples' },
      ],
    },
    {
      text: ' 🔍️ 编写插件',
      collapsed: true,
      items: [
        { text: '✨ 简单介绍', link: '/CodePlugins/Start' },
        { text: '🔥 插件开发指南', link: '/CodePlugins/CookBook' },
        { text: 'VsCode配置', link: '/CodePlugins/Env' },
        { text: '简单示例', link: '/CodePlugins/Simple' },
        { text: '简单参考', link: '/CodePlugins/Exsample' },
        { text: '定时任务', link: '/CodePlugins/Scheduler' },
        { text: '🆕 插件前缀', link: '/CodePlugins/PluginsPrefix' },
        { text: '调用资源目录', link: '/CodePlugins/GetDataPath' },
        { text: '提供配置项', link: '/CodePlugins/PluginsConfig' },
        { text: '调用配置项', link: '/CodePlugins/GetPluginsConfig' },
        { text: '调用数据库', link: '/CodePlugins/PluginsDataBase' },
        { text: '多步会话', link: '/CodePlugins/Resp' },
        { text: '插件帮助', link: '/CodePlugins/PluginsHelp' },
        { text: '✨ 订阅消息', link: '/CodePlugins/Subscribe' },
        { text: '🔧 触发器', link: '/CodePlugins/trigger' },
        { text: '任意位置调用Bot', link: '/CodePlugins/BotCall' },
        { text: '发送消息给主人', link: '/CodePlugins/SendToMaster' },
        { text: '模块方法', link: '/CodePlugins/Class' },
        { text: '实时聊天室', link: '/SP/chat' },
      ],
    },
    {
      text: ' 🧐 编写适配器',
      collapsed: true,
      items: [
        { text: '早柚协议', link: '/CodeAdapter/Protocol' },
        { text: '数据结构', link: '/CodeAdapter/Pack' },
      ],
    },
    {
      text: ' 📄 插件帮助',
      collapsed: true,
      items: [
        { text: 'GenshinUID', link: '/PluginsHelp/GenshinUID' },
        { text: 'StarRailUID', link: '/PluginsHelp/StarRailUID' },
        { text: 'ArknightsUID', link: '/PluginsHelp/ArknightsUID' },
        { text: 'BlueArchiveUID', link: '/PluginsHelp/BlueArchiveUID' },
        { text: 'WzryUID', link: '/PluginsHelp/WzryUID' },
        { text: 'MajsoulUID', link: '/PluginsHelp/MajsoulUID' },
        { text: 'LOLegendsUID', link: '/PluginsHelp/LOLegendsUID' },
        { text: 'ZZZeroUID', link: '/PluginsHelp/ZZZeroUID' },
        { text: 'CS2UID', link: '/PluginsHelp/CS2UID' },
        { text: 'DetlaUID', link: '/PluginsHelp/DeltaUID' },
        { text: 'VAUID', link: '/PluginsHelp/VAUID' },
      ],
    },
  ],
}
