#!/usr/bin/env node
/**
 * 字体切片脚本 - 将 MiSansVF.ttf（可变字体）切成 N 个 woff2 子集
 *
 * 设计要点：
 * 1. 复用现有 Google Fonts Noto Sans SC 风格的 unicode-range 划分（97 个 slice），
 *    保证浏览器只在页面上需要某个 unicode 区间时才下载对应的 woff2。
 * 2. 保留 fvar / gvar 表（即可变字体的 wght 轴），一份 woff2 文件同时支持
 *    150~700 字重，不再为 Medium/Bold/Demibold/Heavy 各自加载一份。
 * 3. 输出：
 *      public/font/MiSans-VF/MiSansVF.{1..97}.woff2
 *      public/font/MiSans-VF/font.css          ← 由 layout.tsx 通过 <link> 加载
 *
 * 用法：
 *   1. 把 MiSansVF.ttf 放到 public/font/MiSans-VF/MiSansVF.ttf
 *   2. node scripts/font-slice.mjs
 *   3. 等待约 30s，控制台会打印每个 slice 的字节数与合计
 *
 * 依赖：
 *   pyftsubset（fonttools，需 `pip install fonttools brotli`）
 */

import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
// 源字体：放在 assets/fonts/ 而非 public/，避免被打进 out/ 部署
const SRC = resolve(ROOT, 'assets/fonts/MiSansVF.ttf')
const OUT_DIR = resolve(ROOT, 'public/font/MiSans-VF')
// 复用项目里现成的任一静态字体的 font.css（划分规则一致）
const REFERENCE_CSS = resolve(
  ROOT,
  'public/font/MiSans-Medium/font.css',
)

if (!existsSync(SRC)) {
  console.error(`❌ 找不到源字体：${SRC}`)
  console.error('   请先把 MiSansVF.ttf 放到 public/font/MiSans-VF/ 下。')
  process.exit(1)
}
mkdirSync(OUT_DIR, { recursive: true })

// ---------- 1. 从参考 font.css 里抠出 97 个 unicode-range ----------
const refCss = readFileSync(REFERENCE_CSS, 'utf-8')
const rangeRegex = /unicode-range:\s*([^;]+);/g
const ranges = []
for (const m of refCss.matchAll(rangeRegex)) ranges.push(m[1].trim())
if (!ranges.length) {
  console.error('❌ 没能从参考 font.css 抠出 unicode-range，请检查文件。')
  process.exit(1)
}
console.log(`📦 共 ${ranges.length} 个 unicode-range slice（沿用 Google Fonts Noto Sans SC 划分）`)

// ---------- 2. 把 "U+ff03,U+ff04,U+ff17-ff19" 转成 pyftsubset 接受的 "U+ff03,U+ff04,U+ff17-ff19" ----------
//   pyftsubset 的 --unicodes 接受相同格式，直接透传即可。

// ---------- 3. 逐个调 pyftsubset ----------
const PYFTSUBSET = process.platform === 'win32' ? 'pyftsubset.exe' : 'pyftsubset'
let totalBytes = 0
let maxBytes = 0
let emptySlices = 0
const cssLines = [
  '/* generated by scripts/font-slice.mjs — MiSans VF (variable font) */',
  '/* 每个 @font-face 只覆盖一个 unicode 区间，浏览器按需下载。 */',
  '/* 单个 woff2 同时支持 wght 150~700，省去 Medium/Bold/Demibold/Heavy 四套独立字体。 */',
]

const t0 = Date.now()
for (let i = 0; i < ranges.length; i++) {
  const idx = i + 1
  const outName = `MiSansVF.${idx}.woff2`
  const outPath = resolve(OUT_DIR, outName)

  const args = [
    SRC,
    `--unicodes=${ranges[i]}`,
    `--output-file=${outPath}`,
    // 输出 woff2（Brotli 压缩）
    `--flavor=woff2`,
    // 让 pyftsubset 同步处理 fvar / gvar（按剩余字形裁切），从而保留 wght 轴
    // 仅保留与轴相关的元数据表（不去掉，否则 STAT / HVAR 会丢）
    `--no-subset-tables+=STAT,HVAR,VVAR,MVAR,cvar`,
    // DSIG（数字签名）对网页字体无意义，丢掉
    `--drop-tables+=DSIG`,
    `--name-IDs=*`,
    `--name-legacy`,
    `--name-languages=*`,
    `--layout-features=*`,
    `--notdef-glyph`,
    `--notdef-outline`,
    `--recommended-glyphs`,
    `--glyph-names`,
    `--symbol-cmap`,
    `--legacy-cmap`,
    `--recalc-bounds`,
    `--recalc-average-width`,
    `--recalc-max-context`,
  ]

  const r = spawnSync(PYFTSUBSET, args, { stdio: ['ignore', 'pipe', 'pipe'] })
  if (r.status !== 0) {
    console.error(`❌ slice ${idx} 失败：${r.stderr?.toString() ?? r.error}`)
    process.exit(1)
  }

  const sz = statSync(outPath).size
  totalBytes += sz
  if (sz > maxBytes) maxBytes = sz
  if (sz < 64) emptySlices++
  if (idx <= 3 || idx === ranges.length || idx % 20 === 0) {
    console.log(
      `   ✓ ${idx.toString().padStart(3)}/${ranges.length}  ${outName.padEnd(20)}  ${(sz / 1024).toFixed(1).padStart(8)} KB`,
    )
  }
}

const elapsed = ((Date.now() - t0) / 1000).toFixed(1)
console.log('')
console.log(`✅ 全部完成（${elapsed}s）`)
console.log(`   合计 ${(totalBytes / 1024 / 1024).toFixed(2)} MB  ·  最大单片 ${(maxBytes / 1024).toFixed(1)} KB`)
if (emptySlices > 0) {
  console.log(`   ⚠ 有 ${emptySlices} 个 slice 文件 < 64 字节（该 unicode 区间字体不含字形，留着也无害）`)
}

// ---------- 4. 生成 font.css ----------
for (let i = 0; i < ranges.length; i++) {
  const idx = i + 1
  cssLines.push(
    `@font-face {`,
    `  font-family: 'MiSans VF';`,
    `  src: url('./MiSansVF.${idx}.woff2') format('woff2-variations'),`,
    `       url('./MiSansVF.${idx}.woff2') format('woff2');`,
    `  font-weight: 150 700;`,
    `  font-style: normal;`,
    `  font-display: swap;`,
    `  unicode-range: ${ranges[i]};`,
    `}`,
  )
}
writeFileSync(resolve(OUT_DIR, 'font.css'), cssLines.join('\n') + '\n', 'utf-8')
console.log(`📝 已生成 font.css（${cssLines.length} 行）`)